{
 "title": "Nanog 77 - Site",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Spine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic Per Spine (bps)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(interface_state_counters_in_octets{role=\"spine\",intf_role=\"leaf\"}[2m])*8) by (device)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Traffic Diff per Spine (bps)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(interface_state_counters_in_octets{role=\"spine\",intf_role=\"leaf\"}[2m])*8) by (device) - sum(rate(interface_state_counters_out_octets{role=\"spine\",intf_role=\"leaf\"}[2m])*8) by (device)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Traffic Per Spine (pps)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(interface_state_counters_in_unicast_pkts{role=\"spine\",intf_role=\"leaf\"}[2m])*8) by (device)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Traffic Diff per Spine (pps)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(interface_state_counters_in_unicast_pkts{role=\"spine\",intf_role=\"leaf\"}[2m])*8) by (device) - sum(rate(interface_state_counters_out_unicast_pkts{role=\"spine\",intf_role=\"leaf\"}[2m])*8) by (device)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Interfaces Status",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "interface_state_oper_status{intf_role=~\"leaf|uplink\", role=\"spine\"}",
     "legendFormat": "{{device}} {{name}} -> {{neighbor}}"
    }
   ]
  },
  {
   "title": "BGP Sessions Status",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "bgp_neighbor_session_state{role=\"spine\"}",
     "legendFormat": "{{device}} {{neighbor_address}}"
    }
   ]
  },
  { "title": "Leaf", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Interfaces Status",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "interface_state_oper_status{intf_role=~\"leaf|uplink\", role=\"leaf\"}",
     "legendFormat": "{{device}} {{name}} -> {{neighbor}}"
    }
   ]
  },
  {
   "title": "BGP Sessions Status",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "bgp_neighbor_session_state{role=\"leaf\"}",
     "legendFormat": "{{device}} {{neighbor_address}}"
    }
   ]
  },
  {
   "title": "Traffic on Leaf > Spine",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(interface_state_counters_in_octets{intf_role=\"uplink\",role=\"leaf\"}[2m])*8) by (device)",
     "legendFormat": "{{device}}  IN"
    },
    {
     "expr": "sum(rate(interface_state_counters_out_octets{intf_role=\"uplink\",role=\"leaf\"}[2m])*8) by (device)",
     "legendFormat": "{{device}} OUT"
    }
   ]
  },
  {
   "title": "Ingress Traffic per Leaf  ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(interface_state_counters_out_octets{role=\"spine\", intf_role=\"leaf\"}[2m])*8) by (neighbor)",
     "legendFormat": "{{neighbor}} from spine"
    },
    {
     "expr": "sum(rate(interface_state_counters_in_octets{role=\"leaf\", intf_role=\"uplink\"}[2m])*8) by (device)",
     "legendFormat": "{{device}} local"
    }
   ]
  }
 ]
}