{
 "title": "Nanog 77 - Device",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "device",
    "query": "label_values(interface_state_counters_in_octets, device)"
   }
  ]
 },
 "panels": [
  {
   "title": "BGP Sessions Status",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "bgp_neighbor_session_state{device=\"$device\"}",
     "legendFormat": "{{device}} {{neighbor_address}}"
    }
   ]
  },
  {
   "title": "BGP Sessions Status",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "interface_state_oper_status{device=\"$device\", intf_role=~\".+\"}",
     "legendFormat": "{{device}} {{name}} > {{intf_role}} >  {{neighbor}}"
    }
   ]
  },
  {
   "title": "Traffic per Uplink on Leaf (bps)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(interface_state_counters_in_octets{device=\"$device\", intf_role=~\".+\"}[2m])*8",
     "legendFormat": "{{name}} IN"
    },
    {
     "expr": "rate(interface_state_counters_out_octets{device=\"$device\", intf_role=~\".+\"}[2m])*8",
     "legendFormat": "{{name}} OUT"
    }
   ]
  },
  {
   "title": "Traffic per interface (bps)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(interface_state_counters_in_pkts{device=\"$device\", intf_role=~\".+\"}[2m])*8",
     "legendFormat": "{{name}} {{intf_role}} IN"
    },
    {
     "expr": "rate(interface_state_counters_out_pkts{device=\"$device\", intf_role=~\".+\"}[2m])*8",
     "legendFormat": "{{name}} {{intf_role}} OUT"
    }
   ]
  }
 ]
}